version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/Lisbon
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: stylelint-config-standard
    versions:
    - 21.0.0
  - dependency-name: stylelint-config-recommended
    versions:
    - 4.0.0
